### ISSUE TITLE
README instructions don't work

### ISSUE THREAD

**Issue by benmoss** [pivotal-cf-experimental/xray#4]
When I launch xray following the README instructions I just get this:
![screen shot 2015-04-30 at 9 30 23 am](https://cloud.githubusercontent.com/assets/239754/7413609/375cc542-ef1b-11e4-9ef0-975034c5e1ef.png)

Seems like assets need to be compiled first.

**Comment by scottruitt** [comment]
thanks, @benmoss, for the issue here and pr over there: https://github.com/pivotal-cf-experimental/xray/pull/6 we're working through a couple of issues around x-ray but will get them fixed asap.

**Comment by rdy** [comment]
this was related to issue #5 which has been resolved
