### ISSUE TITLE
xray doesn't forward special characters to receptor properly

### ISSUE THREAD

**Issue by MarkKropf** [pivotal-cf-experimental/xray#7]
Try using a password with *'s or any other special character, and it gets escaped incorrectly and receptor doesn't validate the credential. Then add the same receptor with credentials in the URI and it quasi works after that.

**Comment by scottruitt** [comment]
thanks, @MarkKropf. added it to top of backlog.

**Comment by rdy** [comment]
fixed in master on story #93644618 in our tracker
